services:
  fortress-app:
    build:
      context: .
      dockerfile: docs/docker-vps/fortress/Dockerfile
      target: php
    image: fortress-laravel:php
    container_name: fortress_app
    restart: unless-stopped
    depends_on:
      - fortress-db
      - fortress-redis
    env_file:
      - .env
    volumes:
      - fortress_storage:/var/www/html/storage
    networks:
      - pangolin

  fortress-web:
    build:
      context: .
      dockerfile: docs/docker-vps/fortress/Dockerfile
      target: nginx
    image: fortress-laravel:nginx
    container_name: fortress_web
    restart: unless-stopped
    depends_on:
      - fortress-app
    volumes:
      - fortress_storage:/var/www/html/storage
    networks:
      - pangolin
    labels:
      - "traefik.enable=false"


  fortress-queue:
    image: fortress-laravel:php
    container_name: fortress_queue
    restart: unless-stopped
    depends_on:
      - fortress-app
    env_file:
      - .env
    command: php artisan queue:work --queue=boletos,receipts,default --sleep=3 --tries=3 --memory=256
    volumes:
      - fortress_storage:/var/www/html/storage
    networks:
      - pangolin

  fortress-scheduler:
    image: fortress-laravel:php
    container_name: fortress_scheduler
    restart: unless-stopped
    depends_on:
      - fortress-app
    env_file:
      - .env
    command: >
      sh -c "while true; do php artisan schedule:run --no-interaction --verbose; sleep 60; done"
    volumes:
      - fortress_storage:/var/www/html/storage
    networks:
      - pangolin

  fortress-db:
    image: mysql:8.0
    container_name: fortress_db
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${FORTRESS_DB_DATABASE}
      MYSQL_USER: ${FORTRESS_DB_USERNAME}
      MYSQL_PASSWORD: ${FORTRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${FORTRESS_DB_ROOT_PASSWORD}
    volumes:
      - fortress_db_data:/var/lib/mysql
    networks:
      - pangolin

  fortress-redis:
    image: redis:7-alpine
    container_name: fortress_redis
    restart: unless-stopped
    command: redis-server --save 60 1000 --appendonly yes
    volumes:
      - fortress_redis_data:/data
    networks:
      - pangolin

volumes:
  fortress_storage:
  fortress_db_data:
  fortress_redis_data:

networks:
  pangolin:
    external: true
