version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortress-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /mnt/user/fortress-app/fortress-laravel:/var/www/html
    depends_on:
      - db
      - redis

  web:
    image: nginx:stable
    container_name: fortress-nginx
    restart: unless-stopped
    ports:
      - "8087:80"
    volumes:
      - /mnt/user/fortress-app/fortress-laravel:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: fortress-mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: fortress
      MYSQL_USER: fortress
      MYSQL_PASSWORD: fortress-secret
      MYSQL_ROOT_PASSWORD: root-secret
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: fortress-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6380:6379"

volumes:
  mysql-data:
