<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'token' => env('POSTMARK_TOKEN'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'bradesco_boleto' => [
        'base_url' => env('BRADESCO_BASE_URL'),
        'client_id' => env('BRADESCO_CLIENT_ID'),
        'client_secret' => env('BRADESCO_CLIENT_SECRET'),
        'cert_path' => env('BRADESCO_TLS_CERT_PATH', env('BRADESCO_CERT_PATH')),
        'cert_password' => env('BRADESCO_TLS_CERT_PASSWORD', env('BRADESCO_CERT_PASSWORD')),
        'key_path' => env('BRADESCO_TLS_KEY_PATH'),
        'key_password' => env('BRADESCO_TLS_KEY_PASS'),
        'webhook_secret' => env('BRADESCO_WEBHOOK_SECRET'),
        'environment' => env('BRADESCO_ENV', 'sandbox'),
        'timeout' => (int) env('BRADESCO_TIMEOUT', 10),
        'fake' => (bool) env('BRADESCO_USE_FAKE', false),
        'id_produto' => env('BRADESCO_ID_PRODUTO'),
        'negociacao' => env('BRADESCO_NEGOCIACAO'),
        'convenio' => env('BRADESCO_CONVENIO'),
        'cod_especie' => env('BRADESCO_COD_ESPECIE'),
        'cnpj_raiz' => env('BRADESCO_CNPJ_RAIZ'),
        'cnpj_filial' => env('BRADESCO_CNPJ_FILIAL'),
        'cnpj_controle' => env('BRADESCO_CNPJ_CONTROLE'),
        'codigo_usuario' => env('BRADESCO_CODIGO_USUARIO'),
        'registra_titulo' => env('BRADESCO_REGISTRA_TITULO', 'S'),
        'tipo_vencimento' => env('BRADESCO_TP_VENCIMENTO', '0'),
        'indicador_moeda' => env('BRADESCO_INDICADOR_MOEDA', '1'),
        'quantidade_moeda' => env('BRADESCO_QTDE_MOEDA', '00000000000000000'),
        'tp_protesto' => env('BRADESCO_TP_PROTESTO', '0'),
        'prazo_protesto' => env('BRADESCO_PRAZO_PROTESTO', '00'),
        'tipo_decurso' => env('BRADESCO_TIPO_DECURSO', '0'),
        'tipo_dias_decurso' => env('BRADESCO_TIPO_DIAS_DECURSO', '0'),
        'tipo_prazo_tres' => env('BRADESCO_TIPO_PRAZO_TRES', '000'),
        'indicador_aceite_sacado' => env('BRADESCO_INDICADOR_ACEITE_SACADO', '2'),
        'sandbox_use_fixtures' => (bool) env('BRADESCO_SANDBOX_USE_FIXTURES', false),
        'sandbox_pdf_url' => env('BRADESCO_SANDBOX_PDF_URL', 'about:blank'),
        'sandbox_payload_overrides' => [
            'debitoAutomatico' => 'N',
            'codigoUsuarioSolicitante' => 'APISERVIC',
            'nuCPFCNPJ' => '12345678',
            'filialCPFCNPJ' => '1018',
            'ctrlCPFCNPJ' => '38',
            'registraTitulo' => '1',
            'idProduto' => '9',
            'nuNegociacao' => '386100000000041000',
            'nuTitulo' => '0',
            'nuCliente' => 'WEBSERVICE',
            'tpVencimento' => '0',
            'indicadorMoeda' => '0',
            'qmoedaNegocTitlo' => '0',
            'cdEspecieTitulo' => '1',
            'cindcdAceitSacdo' => '2',
            'tpProtestoAutomaticoNegativacao' => '0',
            'prazoProtestoAutomaticoNegativacao' => '0',
            'tipoDiasDecursoProt' => '0',
            'tipoDecursoPrazo' => '0',
            'tipoPrazoDecursoTres' => '0',
            'controleParticipante' => '',
            'cdPagamentoParcial' => '',
            'qtdePagamentoParcial' => '0',
            'percentualJuros' => '0',
            'vlJuros' => '0',
            'qtdeDiasJuros' => '0',
            'percentualMulta' => '0',
            'vlMulta' => '0',
            'qtdeDiasMulta' => '0',
            'percentualDesconto1' => '0',
            'vlDesconto1' => '0',
            'dataLimiteDesconto1' => '',
            'percentualDesconto2' => '0',
            'vlDesconto2' => '0',
            'dataLimiteDesconto2' => '',
            'percentualDesconto3' => '0',
            'vlDesconto3' => '0',
            'dataLimiteDesconto3' => '',
            'prazoBonificacao' => '0',
            'percentualBonificacao' => '0',
            'vlBonificacao' => '0',
            'dtLimiteBonificacao' => '',
            'vlAbatimento' => '0',
            'vlNominalTitulo' => '1000.00',
            'vlIOF' => '0',
            'nomePagador' => 'TESTE BE',
            'logradouroPagador' => 'AVENIDA COPACABANA',
            'nuLogradouroPagador' => '237',
            'complementoLogradouroPagador' => '3 ANDAR',
            'cepPagador' => '6050',
            'complementoCepPagador' => '40',
            'bairroPagador' => 'ALPHAVILLE',
            'municipioPagador' => 'BARUERI',
            'ufPagador' => 'SP',
            'cdIndCpfcnpjPagador' => '1',
            'nuCpfcnpjPagador' => '11438390807',
            'endEletronicoPagador' => '',
            'dddFoneSacado' => '0',
            'foneSacado' => '0',
            'bancoDoDebAutomatico' => '237',
            'agenciaDoDebAutomatico' => '2',
            'digitoAgenciaDoDebAutomat' => '7',
            'contaDoDebAutomatico' => '5223',
            'razaoDoDebAutomatico' => '705',
            'codBancoDoProtesto' => '0',
            'agenciaDoProtesto' => '0',
            'nomeSacadorAvalista' => 'A',
            'logradouroSacadorAvalista' => 'A',
            'nuLogradouroSacadorAvalista' => '4',
            'complementoLogradouroSacadorAvalista' => '',
            'cepSacadorAvalista' => '0',
            'complementoCepSacadorAvalista' => '0',
            'bairroSacadorAvalista' => 'D',
            'municipioSacadorAvalista' => 'D',
            'ufSacadorAvalista' => 'SP',
            'cdIndCpfcnpjSacadorAvalista' => '1',
            'nuCpfcnpjSacadorAvalista' => '0',
            'enderecoSacadorAvalista' => 'DD',
            'dddFoneSacadorAvalista' => '11',
            'foneSacadorAvalista' => '24144323',
            'listaMsgs' => [
                ['mensagem' => 'Teste MSG 1'],
                ['mensagem' => 'Teste MSG 2'],
            ],
        ],
    ],

];
