http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    # HTTP to HTTPS redirect router
    main-app-router-redirect:
      rule: "Host(`pangolin.vrios.com.br`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
        
    wordpress-http:
      rule: "Host(`fortressempreendimentos.com.br`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: noop@internal   
      
        
    wordpress-https:
      rule: "Host(`fortressempreendimentos.com.br`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: wordpress-service


    # Next.js router (handles everything except API and WebSocket paths)
    next-router:
      rule: "Host(`pangolin.vrios.com.br`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # API router (handles /api/v1 paths)
    api-router:
      rule: "Host(`pangolin.vrios.com.br`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # WebSocket router
    ws-router:
      rule: "Host(`pangolin.vrios.com.br`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"  # Next.js server

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"  # API/WebSocket server
          
              
    wordpress-service:
      loadBalancer:
        servers:
          - url: "http://wordpress:80"
