name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: >-
            mbstring, pdo_mysql, gd, zip, xml, curl, dom, fileinfo, sqlite3
          tools: composer:v2
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare Application Key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: ESLint
        run: npm run lint

      - name: Prettier Check
        run: npm run format

      - name: Frontend Unit Tests
        run: npm run test:unit

      - name: Frontend Build
        run: npm run build

      - name: PHP Lint
        run: composer lint

      - name: PHPStan (Larastan)
        run: composer stan

      - name: PHP Tests
        run: composer test
